repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.290"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/dosisod/refurb
    rev: v1.21.0
    hooks:
      - id: refurb

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.11.1"
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
